// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false, // Disable to prevent conflicts with Clerk
      flowType: "pkce",
      // Custom lock implementation to avoid Navigator Lock conflicts
      storageKey: "supabase-auth-token",
    },
    global: {
      headers: {
        'X-Client-Info': 'instagram-reels-analytics',
      },
    },
  }
);
